### ISSUE TITLE
Is This in Maven Repo Somewhere?

### ISSUE THREAD

**Issue by pete-proton** [yannick-cw/sane-gen#2]
thanks for the library, but cannot add a dependency on it, since subj. could you help?

**Comment by yannick-cw** [comment]
Hey, sorry this library is not maintained anymore

pete-proton <notifications@github.com> schrieb am Fr. 10. Jan. 2020 um
16:50:

**Comment by pete-proton** [comment]
@yannick-cw, that's a pity. but thanks anyway!

**Comment by pete-proton** [comment]
@yannick-cw could you update the readme to indicate that library is not maintained? or do you need help with that in a form of a PR, for example? might be helpful to others.
